version: "3"

services:
    app:
        build: .docker/app
        volumes:
            - .:/app
            - /var/cache
        depends_on:
            - mariadb
            - redis

    app-http:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - .:/app
            - .docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    mariadb:
        image: mariadb:latest
        ports:
            - "3306:3306"
        volumes:
            - mariadb-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root

    redis:
        image: redis:latest
        volumes:
            - redis-data:/data
            - .docker/redis/redis.conf:/usr/local/etc/redis/redis.conf

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8100:80"
        environment:
            PMA_HOST: mariadb
            MYSQL_ROOT_PASSWORD: root

volumes:
    mariadb-data:
    redis-data:
